### ISSUE TITLE
Published in Flathub

### ISSUE THREAD

**Issue by xylo04** [flathub/radio.k0swe.Kel_Agent#1]
@hfiguiere or @barthalion, is there any action needed to get this published at this point? I'm waiting for this to appear at https://flathub.org/apps/details/radio.k0swe.Kel_Agent, but so far that's still "not found."

**Comment by hfiguiere** [comment]
@nedrichards any idea?

**Comment by bilelmoussaoui** [comment]
It's marked as a console application in https://github.com/k0swe/kel-agent/blob/main/assets/radio.k0swe.Kel_Agent.metainfo.xml#L2 and we don't display those on the website frontend yet.

**Comment by xylo04** [comment]
Ok, that makes sense. I was waiting for it to show up in either the website or the Pop_OS store, but I'm able to install from command line as expected: `flatpak install flathub radio.k0swe.Kel_Agent`. Thanks!
