### ISSUE TITLE
Not appearing in flathub store

### ISSUE THREAD

**Issue by xylo04** [flathub/radio.k0swe.Kel_Agent#9]
@hfiguiere, @barthalion: this package is no longer showing up on the flathub website. At one time I was able to find it at https://flathub.org/apps/details/radio.k0swe.Kel_Agent, but now that page 404s. Also, trying to install or update on the command line doesn't work.

I know at one time we had discussed that this was being filtered out of certain views because it's marked as a command-line application, and flathub is geared toward GUI apps. Perhaps that has something to do with this?

**Comment by xylo04** [comment]
Oh, apparently we discussed in #1 that the website has never shown CLI apps, so that's not a regression. However, I updated this package about 8 hours ago (well beyond the 3 hour default publish time), and `flatpak update radio.k0swe.Kel_Agent` is still not updating. Any ideas? Maybe the pipeline is just behind.

**Comment by xylo04** [comment]
Actually, it was only merged about 4 hours ago. I'll just be more patient; sorry for the noise.

**Comment by hfiguiere** [comment]
for the record I have no access to any of these part. So assigning to me is a waste of everyone's time.
